api:
    resource: ../src/Application/Http/**/{Command,Query}/**/*Handler.php
    type: attribute
    prefix: 'api'

login:
    path: /api/auth/login

api_refresh_token:
    path: /api/auth/token/refresh