api:
    resource: ../src/**/Api/*Handler.php
    type: attribute
    prefix: 'api'
    name_prefix: api

login_check:
    path: /api/auth/login_check

api_refresh_token:
    path: /api/auth/token/refresh